export const PALETTE_REFERENCES = [
  {
    id: "soft-tech",
    name: "Soft Tech Pastels",
    nameZh: "柔和科技粉彩",
    desc: "主打低压、长时间练习也不刺眼的数字产品色谱。",
    source: "Realtime Colors",
    href: "https://www.realtimecolors.com/",
    swatches: ["#0A0D1A", "#F5F7FF", "#A78BFA", "#38BDF8", "#FBBF24"],
    tags: ["深浅对照", "强调色清晰", "对比稳定"],
  },
  {
    id: "pastel-mint",
    name: "Pastel Mint Lilac",
    nameZh: "薄荷紫雾",
    desc: "从 pastel 方向里挑更适合毛玻璃和冷白背景的轻色卡。",
    source: "Color Hunt",
    href: "https://colorhunt.co/?q=pastel",
    swatches: ["#C7D2FE", "#E8E6FF", "#BAE6FF", "#FECDD3", "#A7F3D0"],
    tags: ["轻盈", "偏 UI", "适合浅色"],
  },
  {
    id: "sage-website",
    name: "Sage Practice UI",
    nameZh: "自然练习界面",
    desc: "偏 Huemint 风格的双强调网站配色，适合做长期使用的绿色方向。",
    source: "Huemint",
    href: "https://www.huemint.com/website-2",
    swatches: ["#F0FAF5", "#EEF2FF", "#34D399", "#818CF8", "#D97706"],
    tags: ["自然", "耐看", "训练型产品"],
  },
  {
    id: "warm-paper",
    name: "Warm Paper Grain",
    nameZh: "暖纸颗粒",
    desc: "让 grain / linen 方向不只是米黄，而是带一点柔和金色和冷白平衡。",
    source: "Huemint",
    href: "https://www.huemint.com/website-2",
    swatches: ["#FDF8F0", "#FFF8F0", "#FDE68A", "#F59E0B", "#B45309"],
    tags: ["纸感", "暖调", "层次更稳"],
  },
  {
    id: "glass-recipe",
    name: "Glass Surface Recipe",
    nameZh: "毛玻璃参数",
    desc: "用于卡片材质的推荐起点：中高模糊、较高饱和、轻边框和柔和内高光。",
    source: "Glassmorphism",
    href: "https://www.glassmorphism.com/",
    swatches: ["rgba(255,255,255,0.15)", "blur(20px)", "rgba(255,255,255,0.30)", "#FFFFFF", "#0A0D1A"],
    tags: ["blur 20", "border 0.3", "radius 20"],
    isMeta: true,
  },
];
